linkstack:
  serverAdmin: info@fmj.studio
  serverName: linkstack.helm.private
  logLevel: warn
  timeZone: Europe/Berlin
  phpMemoryLimit: 512M
  uploadMaxFileSize: 32M

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: development-issuer
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/connection-proxy-header: "upgrade"
  tls:
    - secretName: linkstack-ingress-tls
      hosts:
        - linkstack.helm.private

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true
