# This is a basic workflow to help you get started with Actions

name: Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  find-charts:
    name: Find Charts
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.charts.outputs.folders }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - id: charts
        uses: kmanimaran/list-folder-action@v4
        with:
          path: ./charts

  lint-charts:
    name: Lint Applications
    needs: [find-charts]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.chart }}
    strategy:
      matrix:
        chart: ${{ fromJson(needs.find-charts.outputs.charts )}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: dev
      
      - name: Scan ${{ matrix.chart }}
        id: kube-lint-scan-chart
        uses: stackrox/kube-linter-action@v1
        with:
          directory: charts/${{ matrix.app }}
