name: Release Helm Chart

on:
  workflow_dispatch:
  push:
    branches:
      - main # or your default branch
    #tags:
    #  - 'v*' # Trigger on version tags like v1.0.0
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for chart-releaser-action

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.15.0 # Specify your desired Helm version
      
      - name: 'Configure Git'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1.7.0 # Use the desired version of the action
        with:
          skip_upload: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Token for authentication
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true

      - name: 'Move to upload path'
        run: |
          mkdir -p ./dist/charts
          mv .cr-release-packages/* ./dist/charts
          make pre-fetch && make index
          ls -R ./dist/
          
      - name: 'Upload Packaged Charts as Artifacts'
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'dist'
          path: 'dist/'
